install:
  - ps: Install-Product node 6 x64
  - npm install -g npm@latest
  - node --version
  - npm --version
  - npm install

test_script:
  - node index.js --color

# Don't actually build.
build: off
